import "./globals.css";
import { Inter, Borel, Kosugi_Maru } from "next/font/google";
import { ThemeProvider } from "@/components/theme-provider";
import Nav from "@/components/nav";

const k_maru = Kosugi_Maru({
  subsets: ["cyrillic", "latin"],
  style: "normal",
  weight: "400",
});

const borel = Borel({
  subsets: ["latin"],
  style: "normal",
  weight: "400",
});

export const metadata = {
  title: "Persona",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={k_maru.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem
          disableTransitionOnChange
        >
          <div className="w-screen min-h-screen flex flex-col items-center">
            <Nav />
            {children}
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
